### ISSUE TITLE
List of breaking changes?

### ISSUE THREAD

**Issue by paglias** [voltrue2/in-app-purchase#131]
Hi,

we're using version 1.1.x of this module, I'd like to upgrade to the newest version but I've not been able to find if the lib follows semver, so no breaking changes until version 2 or if there have been some breaking changes between 1.1 and 1.8, in that case would it be possible to get a list of such changes?

**Comment by voltrue2** [comment]
Hello,

Here are the list of major changes since 1.1 (Not necessarily breaking changes, though):

- `.validate()` can now automatically detect receipt type instead of requiring `iap.APPLE, iap.GOOGLE etc`. I am pasting the section of README here:

>As of version 1.4.0, we now have built-in auto-service detection in `.validate(receipt, callback)` and > `.validateOnce(receipt, secretPubKey, callback)`.

- Support for Promise added.

- Support for Roku added.

- Support for Google validation by Google APIs added

I believe there are no breaking changes, but please let me know if upgrading the package breaks in anyway.

Cheers

**Comment by voltrue2** [comment]
As of `v1.8.4`, the module no longer supports node.js version 0.12.

**Comment by paglias** [comment]
@voltrue2 thanks! I've been able to upgrade without problems :)

**Comment by voltrue2** [comment]
Awesome!
