### ISSUE TITLE
How to tell if the receipt is for production or sandbox?

### ISSUE THREAD

**Issue by comtaler** [voltrue2/in-app-purchase#185]
After calling `validate` function and validation is successful, is there a way to tell if the receipt is validated with prod or sanbox? If not, can this be added?

**Comment by hermosillo8** [comment]
You can set whether the receipt you are validating is prod or sandbox by using test: true for sandbox or false for production on iap.setup(). See README  in the docs for an example.

**Comment by comtaler** [comment]
For iOS, when trying to validate with prod, it can still fall back to validate with sandbox.

**Comment by voltrue2** [comment]
@comtaler Yes it does fallback to sandbox validation if the first production validation fails.
Would you give me an insight as to why you need to know whether the validation was sandbox or production?

Cheers

**Comment by voltrue2** [comment]
No response. Closing.

**Comment by jpoag** [comment]
The problem is that there is information lost: did you use sandbox or production? If we could specify to ONLY use production or ONLY use sandbox this wouldn't be an issue as we could use settings to deduce this information.

Ideally, just add a field to the response object IF (and only if) you used sandbox.

We use this information to throw away Analytics.  Or to catch someone trying to use a sandbox receipt who is obviously not a tester.

**Comment by mrpuzzler** [comment]
We need to filter sandbox purchases too. Is it possible to make update on this?

**Comment by voltrue2** [comment]
Hello, I understand the need for this to happen.
  
I think adding another Boolean property to the validated data to tell if its sandbox or not would suffice?
  

  
Cheers!
  

  
  

  
  
>

**Comment by comtaler** [comment]
That works for me

**Comment by jpoag** [comment]
Sounds great. Defaults to falsey/undefined?

Thanks again!

**Comment by voltrue2** [comment]
Thank you all for brining this up! The new property in validated data `sandbox` has been added to Apple and Amazon!
Defaults to `false` or `undefined`.

b7bd5a894cfa267d8f5c70009edbfca840ef8171

**Comment by jpoag** [comment]
Thank you so much!
