### ISSUE TITLE
CERT_UNTRUSTED occurs for apple validate requests

### ISSUE THREAD

**Issue by psaini14** [voltrue2/in-app-purchase#20]
The send function in apple.js returns the error "CERT_UNTRUSTED" to the validatePurchase callback, and the check for data.status results in the process terminating, as data is null in this case.

If send is modified to the following ("rejectUnauthorized : false" added), everything works fine.

function send(url, content, cb) {
	var options = {
		encoding: null,
		url: url,
		body: content,
		json: true,
		rejectUnauthorized : false
	};
	request.post(options, function (error, res, body) {
		return cb(error, res, body);
	});
}

**Comment by voltrue2** [comment]
Hi 

Thanks a lot for reporting this.
Would you mind giving me a bit more details on how you get this error? and where exactly the code fails with an uncaught exception?

I implemented a possible fix for this issue here: https://github.com/voltrue2/in-app-purchase/commit/3cf73361131323afc28763dec993547b0403e833

I am assuming where the code fails, but it would help me tremendously if you could point to me the block of code where it fails

Thanks in advance

**Comment by psaini14** [comment]
Sure.  The uncaught exception occurred at line 68.  It looks like your fix addresses that part of the problem.  Thanks!

My requests to both live and sandbox resulted in the CERT_UNTRUSTED response.  When I changed the request options to include "rejectUnauthorized : false" as mentioned above, I was able to get the expected response from Apple.

**Comment by voltrue2** [comment]
Thank you for the info and checking the code.

I have merged the fix and published the updated version 0.5.3. This version contains the fix to this apple issue and a typo fix in amazon.js that you found.

Thanks for the help!
