### ISSUE TITLE
general persistence of receipt questions

### ISSUE THREAD

**Issue by bearinld004** [voltrue2/in-app-purchase#208]
@voltrue2,

not really an issue, but more of a general questions in regard to in-app-purchase receipt. what would be the general strategy to save the receipt in the backend (database schema).

I see there is a lot of choices i can use after finishing the transaction in the frontend ios has transactionReceipt, appStoreId, then also after validating there is unique_id. haven't tested the android yet but im sure there is a bunch of ids. there too. 

In your experience which one is good to use as a unique id for me to make sure the user is not submitting their receipt twice? 

Thanks!

**Comment by voltrue2** [comment]
Hello,
  

  
For iOS I would usually go with original_transaction_id along with you application’s unique user ID. Both columns should be indexed so when you check for duplicate submission for the user the database scan is fast and light.
  

  
I hope this helps. I’m currently working on changing the android validation so that you will only need purchase token to validate.
  

  
Cheers!
  

  
  

  
  
>

**Comment by bearinld004** [comment]
Perfect thanks for the feedback and insight! I never knew that having two indexes can help with db performance. I just googled it and there is a term for it too composite index!
