### ISSUE TITLE
What is the difference between validate and validateOnce()

### ISSUE THREAD

**Issue by bander-saeed94** [voltrue2/in-app-purchase#244]
What is the difference between validate and validateOnce function. 
Can you please clarify more.

**Comment by voltrue2** [comment]
Hello,

`validate()` requires validation credentials such as shared password and/tokens provided via configurations. This makes this function a validation for one application only.
`validateOnce()` requires validation credentials as function arguments so that you need to "feed" these credentials when you validate a receipt. This effectively allows you to change validation credentials if necessary making this function a validation for multiple applications.
I hope this clarifies.

Cheers

**Comment by bander-saeed94** [comment]
Thanks. clear

**Comment by voltrue2** [comment]
Awesome.
