### ISSUE TITLE
Google receipt

### ISSUE THREAD

**Issue by skellertor** [voltrue2/in-app-purchase#52]
In the documentation you say that the google receipt is an object with two top level key: "data" and "signature". What is the value of "data" supposed to be?

**Comment by voltrue2** [comment]
Hello

Thank you for reaching out.
The data property is the signed receipt your client gets from Google.

I will have a look at the documentation again and improve this part to not create confusion.

Best

**Comment by skellertor** [comment]
Okay lets say I get this back from google:
{
"purchase" : {
        "productId" : "com.product.product", 
        "orderId" : "", 
        "purchaseTime" : 1.466519385349E12, 
        "developerPayload" : "3546......", 
        "signature" : "base64 string", 
        "purchaseState" : 0, 
        "token" : "blahblashbleung", 
        "packageName" : "com.product.app"
    }
}

I create an object like this?
```{ data: JSON.stringify(purchase), signature: purchase.signature }```

Is this correct?  The reason I ask is I keep getting a validation error.  It says "failed to validate purchase".

In verbose mode it says "<Google> Failed against live public key: [Error: failed to validate purchase]" and "<Google> Failed against sandbox public key: [Error: failed to validate purchase]"

**Comment by voltrue2** [comment]
The JSON you have their seems to contain "signature" in "data". 
If you look at `in-app-purchase/test/receipts/google` file in the module, you will see a sample of this.

Cheers

**Comment by igorescobar** [comment]
Hey guys... I'm here just do add a few things that may help further problems related with "failed to validate purchase" for Google Receipts.

Here are a checklist that you could do in order to fix the issue.
1 - Make sure that your keys are valid.
2 - Make sure the first level of your structure is right... like this:
```javascript
{
  data: "{....}", // stringified json
  signature: ""
}
```
3 - Make sure that NOTHING has changed from the original Google Response inside of the `data` attribute. I've already caught problems when developers de-serialize the `data` and when they serialize it again to json stringify it the order of the attributes has changed so this may be silly but this can give you a lot of headache, specially if you have a distributed architecture and this message has to travel over the wire. 
4 - If the case #3 is your case here is a small script that ilutrates the problem:
```node
const iap = require('in-app-purchase')
iap.config({
  // .....
})

iap.setup((error) => {
  let dataOrder = ['orderId', 'packageName', 'productId', 'purchaseTime', 'purchaseState', 'purchaseState', 'purchaseToken', 'autoRenewing'],
      brokenReceipt = {"data":"……..","signature":"….."},
      objectReceipt = JSON.parse(brokenReceipt["data"]),
      newData = {}

  dataOrder.forEach((k) => newData[k] = objectReceipt[k])
  brokenReceipt['data'] = JSON.stringify(newData)
  console.log("FIXED RECEIPT: ", JSON.stringify(brokenReceipt))

  iap.validate(iap.GOOGLE, brokenReceipt, (error, response) => console.log(error, response))
});
```
The script bellow will fix the receipt for you in order to pass validations if that is your case.

**Comment by mystikxkemix** [comment]
@igorescobar : in your example, in yout dataOrder array there is twice purchaseState. Is it a mistake ?
