### ISSUE TITLE
[IOS]  iap.getPurchaseData does not return "is_trial_period" flag

### ISSUE THREAD

**Issue by meoz** [voltrue2/in-app-purchase#80]
After validation of the receipt and if successful I call iap.getPurchaseData to get all purchases, only the returned data does not contain "is_trial_period" and several other fields like "original_purchase_date" which are part of the receipt. 
Any reason why those data-fields are left out ? Do I have to manually read out the original receipt to get the missing fields afterall ?

**Comment by voltrue2** [comment]
Hello

Thanks for reaching out. 
When I added iap.getPurchadeData(), I meant it to me a convenient API to shortcut the parsing of the actual response of each validation that's why it does not cover all fields, but I suppose we I should extend it to cover all fields. If you have suggestions on as to how I should go about it, I'm all ears! 

Lastly I am exposing the raw response, so you shouldn't be stuck but I can implement the update as soon as I get the chance. 

Cheers

**Comment by meoz** [comment]
Thanks! for the swift reply.

Like you said it does not pose too much of a problem since I still have the raw receipt to read out the fields. But it would be nice if it all could be done through the module.

It first sight I've the following fields in my receipt, would be great if you could add them:

        "quantity"
        "product_id"
        "transaction_id"
        "original_transaction_id"
        "purchase_date"
        "purchase_date_ms"
        "purchase_date_pst"
        "original_purchase_date"
        "original_purchase_date_ms"
        "original_purchase_date_pst"
        "expires_date"
        "expires_date_ms"
        "expires_date_pst"
        "web_order_line_item_id"
        "is_trial_period"

**Comment by voltrue2** [comment]
Hello

Sounds fair. Since the module supports 4 different platforms, I may have to add or modify things to make sure it's all consistent, but I think I'll extend the method.

Cheers

**Comment by claesjacobsson** [comment]
+1

**Comment by voltrue2** [comment]
Hello,

Thank you for your input. I have now released a new version of the package on npm. v1.2.0

This version parses all fields returned from each service and make them all available through `.getPurchaseData()`.

Cheers
